### ISSUE TITLE
Copy existing Fleamarket Website: Static pages and amendments

### ISSUE THREAD

**Issue by treviser** [twanda/fleamarket-zug#1]
The existing website is [www.flohmarkt-zug.ch](url) 
It is in German and English, the default language is German. The existing website is built on Odoo 12.
The new website has a temporary URL as [https://flohmarkt-zug.twanda-hosting.ch](url) 
It is built on Odoo 14 (Docker). 
Both are dedicated databases, no multi-company. Admin user has the same credentials for both databases (see skype Siddharth for the password).

The existing website has to be copied to Odoo14 in both languages by building a new Website using the features and functionalities of the new Website Builder, do not copy QWeb Views! It should look similar, but it must not be pixel-equal, it should take advantage of the new Website Builder building blocks and possibilities.

The original website was built with theme "Real Estate" and color preset 1 (see https://apps.odoo.com/apps/themes/14.0/theme_real_estate/ )

Please set the proper general theme options for the color scheme and fonts and headings etc.

**Comment by treviser** [comment]
@candidroot Good exercise for somebody who needs to learn the new website builder ;-)

**Comment by candidroot** [comment]
@treviser Please check it https://flohmarkt-zug.twanda-hosting.ch/ 

Let me know if you want to change anything or if something is missing from old website.

**Comment by treviser** [comment]
@candidroot Would be nice if you could add the german translations also.

One thing I would like to have, but I'm not sure how to achieve it. In the new Website builder you can untick the theme option "Show Header", then the ugly page header disappears. Unfortunately also the Hamburger menu button disappears. Is it possible the make the header disappear but nevertheless showing the Hamburger menu the same way as in the old website?

**Comment by candidroot** [comment]
@treviser Yes, I will update translation to all the pages one by one as i have completed with Homepage today. 

Regarding Hamburger menu we will check it and it is required customization then can we do it ? OR this website should be completed with only configuration of default Odoo 14.

**Comment by treviser** [comment]
@candidroot 
If it needs customization, it is a serious design flaw (regression) by Odoo. Then we should think about generic and reasonable way to handle that option in general. Or file a bug report.

**Comment by candidroot** [comment]
@treviser Please check translation for pages, Let me know if anything is missing

**Comment by treviser** [comment]
Thanks!
